# Temel olarak Python 3.9 tabanlı bir imaj kullanalım
FROM python:3.9

# Çalışma dizinini /app olarak ayarlayalım
WORKDIR /app

# Gerekli paketleri kurmak için requirements.txt dosyasını kopyalayalım
COPY requirements_api.txt .

# Paketleri yükleyelim
RUN pip install --no-cache-dir -r requirements.txt

# Çalıştırılabilir Python dosyasını kopyalayalım
COPY api.py .

# Flask uygulamasını çalıştırmak için gerekli komut
CMD ["python", "api.py"]
